<div class="wrap rpbt_cache">
	<h1><?php _e( 'Custom Post Type Cleanup', 'custom-post-type-cleanup' ); ?></h1>
	<?php echo $notice; ?>
	<div class="notice">
		<p>
			<?php _e( 'There are no unused custom post type posts found.', 'custom-post-type-cleanup' ); ?>
		</p>
	</div>
	<p>
		<?php echo $doc_link; ?>
	</p>
	<p>
		<?php 
			printf(
		 		/* translators: %s: wp-admin plugin page url */
				__( '<a href="%s">De-activate this plugin</a> or try again later.', 'custom-post-type-cleanup' ),
				esc_url( $plugin_url )
			);
		?> 
	</p>
	<hr>
	<p>
		<?php
			/* translators: %s: plugin link */
			printf( __( 'This page is generated by the %s plugin.', 'custom-post-type-cleanup' ), $plugin_link );
		?>
	</p>
</div>