<div class="wrap">
	<h1><?php _e( 'Custom Post Type Cleanup', 'custom-post-type-cleanup' ); ?></h1>
	<?php echo $notice; ?>
	<p>
	<?php if ( $notice ) : ?>
		<?php _e( 'Reload this page to see the unused post types in the admin menu or follow the links below.', 'custom-post-type-cleanup' ); ?><br/>
		<?php _e( 'The post types are registered for the next 10 minutes.', 'custom-post-type-cleanup' ); ?>
	<?php else : ?>

		<?php
		/* translators: %s: 'custom post type' or 'custom post types' (single/plural) */
		printf(
			_n(
				'The following %s was registered by this plugin',
				'The following %s were registered by this plugin',
				count( $registered_post_types ), 'custom-post-type-cleanup'
			), $type_str
		);
		?>
		:
	<?php endif; ?>
	</p>
	<p><strong><?php _e( 'Custom Post Types', 'custom-post-type-cleanup' ); ?></strong>
	<ul>
	<?php foreach ( $registered_post_types as $post_type ) : ?>
		<li><a href="<?php echo admin_url( 'edit.php?post_type=' . $post_type ); ?>"><?php echo $post_type; ?></a></li>
	<?php endforeach; ?>
	</ul>
	<hr>
	<p>
		<?php
		/* translators: %s: 'custom post type' or 'custom post types' (single/plural) */
		printf(
			_n(
				'Unregister the unused %s (registered by this plugin) by clicking the following link',
				'Unregister the unused %s (registered by this plugin) by clicking the following link',
				count( $registered_post_types ), 'custom-post-type-cleanup'
			),
			$type_str
		);
		?>
		<br/>
		<a href="<?php echo $admin_url; ?>"><?php _e( 'Un-register the post types registered by this plugin', 'custom-post-type-cleanup' ); ?></a><br/>
	</p>
	<hr>
	<p>
		<?php
			/* translators: %s: plugin link */
			printf( __( 'This page is generated by the %s plugin.', 'custom-post-type-cleanup' ), $plugin_link );
		?>
	</p>
</div>
